# Generated by Django 5.2.4 on 2025-08-17 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_personal_id_alter_ticket_ticket_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian_id', models.CharField(max_length=16)),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('birth_certificate_no', models.CharField(blank=True, max_length=50, null=True)),
                ('school_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='personal_id',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='dependent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.dependent'),
        ),
    ]
