# Generated by Django 5.2.4 on 2025-08-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_dependent_alter_ticket_personal_id_ticket_dependent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('VVIP', 'VVIP'), ('VIP', 'VIP'), ('REGULAR', 'Regular'), ('ADULT', 'Adult'), ('CHILD', 'Child')], default='REGULAR', max_length=10),
            preserve_default=False,
        ),
    ]
